# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-TwzbMZeMOZB_UGZEnXevRgwCFq7UFuD
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
df = pd.read_csv('HHS_Unaccompanied_Alien_Children_Program data.csv')

df.head()

df.info()

# Convert date
df['Date'] = pd.to_datetime(df['Date'])

# Sort by date
df = df.sort_values(by='Date')

# Check missing values
df.isnull().sum()

df.columns = [
    'Date',
    'Intake_CBP',
    'In_CBP',
    'Transferred_to_HHS',
    'In_HHS',
    'Discharged'
]

df.dtypes

# Remove commas if present
df['In_HHS'] = df['In_HHS'].astype(str).str.replace(',', '')
df['Discharged'] = df['Discharged'].astype(str).str.replace(',', '')

# Convert to numeric
df['In_HHS'] = pd.to_numeric(df['In_HHS'], errors='coerce')
df['Discharged'] = pd.to_numeric(df['Discharged'], errors='coerce')

df.dtypes

#df[['In_HHS', 'Discharged']].isnull().sum()

df = df.dropna(subset=['In_HHS', 'Discharged'])

df['Discharge_Effectiveness'] = df['Discharged'] / df['In_HHS']

# Transfer Efficiency
df['Transfer_Efficiency'] = df['Transferred_to_HHS'] / df['In_CBP']

# Discharge Effectiveness
df['Discharge_Effectiveness'] = df['Discharged'] / df['In_HHS']

# Throughput
df['Throughput'] = df['Discharged'] / df['Intake_CBP']

#CBP BACKLOG
df['CBP Backlog']  = df['Intake_CBP'] - df['Transferred_to_HHS']

#HHS Backlog
df['HHS Backlog']  = df['Transferred_to_HHS'] - df['Discharged']

#Backlog
df['Backlog']  = df['CBP Backlog'] + df['HHS Backlog']

df['Total_system_load']  = df['In_CBP'] + df['In_HHS']

#Bottleneck score
df['CBP_Bottleneck_Score'] = abs(df['CBP Backlog']) / df['Total_system_load']

df['HHS_Bottleneck_Score'] =  abs(df['HHS Backlog'])  / df['Total_system_load']

# Calculate discharge stability
df['Discharge_Stability'] = df['Discharged'].rolling(7, min_periods=1).std() / df['Discharged'].rolling(7, min_periods=1).mean()
df['Outcome_Stability_Score'] = 1 - df['Discharge_Stability'].fillna(0)

# Calculate average stay proxy
df['Avg_Stay_Proxy_HHS'] = df['In_HHS'] / df['Discharged'].replace(0, np.nan)

df.describe()

# Calculate flow balance
df['CBP_Flow_Balance'] =  df['Transferred_to_HHS']- df['Intake_CBP']
df['HHS_Flow_Balance'] = df['Discharged'] - df['Transferred_to_HHS']

# Extract temporal features
df['Year'] = df['Date'].dt.year
df['Month'] = df['Date'].dt.month
df['Month_Name'] = df['Date'].dt.strftime('%B')
df['Day_of_Week'] = df['Date'].dt.dayofweek
df['Day_Name'] = df['Date'].dt.strftime('%A')
df['Week'] = df['Date'].dt.isocalendar().week
df['Quarter'] = df['Date'].dt.quarter
df['Is_Weekend'] = (df['Day_of_Week'] >= 5).astype(int)

# Calculate moving averages
for window in [7, 14, 30]:
    df[f'Transfer_Efficiency_MA{window}'] = df['Transfer_Efficiency'].rolling(window, min_periods=1).mean()
    df[f'Discharge_Effectiveness_MA{window}'] = df['Discharge_Effectiveness'].rolling(window, min_periods=1).mean()
    df[f'HHS_Care_MA{window}'] = df['In_HHS'].rolling(window, min_periods=1).mean()

df.to_csv("cleaned_dataset.csv", index=False)

from google.colab import files
files.download("cleaned_dataset.csv")

plt.figure(figsize=(12,6))



plt.plot(df['Date'], df['In_HHS'], label='In HHS Care')

plt.title('Care Pipeline Flow Over Time')
plt.xlabel('Date')
plt.ylabel('Number of Children')
plt.legend()
plt.grid()
plt.show()

plt.figure(figsize=(12,6))
plt.plot(df['Date'], df['In_HHS'], label='Transferred to HHS')
plt.title('Care Pipeline Flow Over Time')
plt.xlabel('Date')
plt.ylabel('Number of Children')
plt.legend()
plt.grid()
plt.show()

plt.figure(figsize=(12,6))
plt.plot(df['Date'], df['Discharged'], label='Discharged')
plt.title('Care Pipeline Flow Over Time')
plt.xlabel('Date')
plt.ylabel('Number of Children')
plt.legend()
plt.grid()
plt.show()

plt.figure(figsize=(12,6))
plt.plot(df['Date'], df['In_CBP'], label='Intake_CBP')
plt.title('Care Pipeline Flow Over Time')
plt.xlabel('Date')
plt.ylabel('Number of Children')
plt.legend()
plt.grid()
plt.show()

plt.figure(figsize=(12,6))

plt.plot(df['Date'], df['Transfer_Efficiency'], label='Transfer Efficiency')


plt.title('Efficiency Trends')
plt.xlabel('Date')
plt.ylabel('Efficiency Ratio')
plt.legend()
plt.grid()
plt.show()

plt.figure(figsize=(12,6))
plt.plot(df['Date'], df['Discharge_Effectiveness'], label='Discharge Effectiveness')
plt.title('Efficiency Trends')
plt.xlabel('Date')
plt.ylabel('Efficiency Ratio')
plt.legend()
plt.grid()
plt.show()

plt.figure(figsize=(12,6))

plt.plot(df['Date'], df['CBP Backlog'], label='CBP Backlog')
plt.plot(df['Date'], df['HHS Backlog'], label='HHS Backlog')

plt.title('Backlog Accumulation Trend')
plt.xlabel('Date')
plt.ylabel('Backlog')
plt.legend()
plt.grid()
plt.show()



# Identify days with high backlog
high_backlog = df[df['Backlog'] > df['Backlog'].mean()]

high_backlog[['Date', 'Backlog']]

kpi = {
    "Avg Transfer Efficiency": df['Transfer_Efficiency'].mean(),
    "Avg Discharge Effectiveness": df['Discharge_Effectiveness'].mean(),
    "Avg Throughput": df['Throughput'].mean(),
    "Max Backlog": df['Backlog'].max()
}

kpi

df['Imbalance'] = df['Intake_CBP'] - df['Discharged']

# Mark imbalance days
df['High_Imbalance'] = df['Imbalance'] > 0

# Find continuous imbalance periods
df['Imbalance_Group'] = (df['High_Imbalance'] != df['High_Imbalance'].shift()).cumsum()

imbalance_periods = df[df['High_Imbalance']].groupby('Imbalance_Group').agg({
    'Date': ['min', 'max'],
    'Imbalance': 'mean'
})

imbalance_periods

# Cumulative backlog
plt.figure(figsize=(12,6))
df['Cumulative_Backlog'] = df['Imbalance'].cumsum()

plt.figure()
plt.plot(df['Date'], df['Cumulative_Backlog'])
plt.title("Accumulation of Unresolved Cases")
plt.show()

# Extract day of week
df['Day'] = df['Date'].dt.day_name()

# Weekday vs Weekend
df['Day_Type'] = df['Day'].apply(lambda x: 'Weekend' if x in ['Saturday', 'Sunday'] else 'Weekday')

# Compare efficiency
weekday_weekend = df.groupby('Day_Type')[['Transfer_Efficiency', 'Discharge_Effectiveness']].mean()

weekday_weekend

plt.figure(figsize=(12,6))
weekday_weekend.plot(kind='bar')
plt.title("Weekday vs Weekend Efficiency")
plt.show()

df['Month'] = df['Date'].dt.to_period('M')

monthly_trends = df.groupby('Month')[[
    'Transfer_Efficiency',
    'Discharge_Effectiveness',
    'Backlog'
]].mean()

monthly_trends

plt.figure(figsize=(12,6))
monthly_trends.plot()
plt.title("Month-over-Month Trends")
plt.show()

# Extract month name
df['Month_Name'] = df['Date'].dt.month_name()

seasonal_pattern = df.groupby('Month_Name')[[
    'Transfer_Efficiency',
    'Discharge_Effectiveness',
    'Backlog'
]].mean()

seasonal_pattern = seasonal_pattern.reindex([
    'January','February','March','April','May','June',
    'July','August','September','October','November','December'
])

seasonal_pattern

seasonal_pattern.plot()
plt.title("Seasonal Pattern Analysis")
plt.show()

df.to_csv("cleaned_dataset.csv", index=False)

from google.colab import files
files.download("cleaned_dataset.csv")

